version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: db_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: adsmurai
      MYSQL_USER: adsmurai
      MYSQL_PASSWORD: adsmurai
      MYSQL_ROOT_PASSWORD: adsmurai
