App\Domain\Safebox\ForbiddenPassword:
  type: entity

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    plainPassword:
      type: string
      column: plain_password
